version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'studytimes'
      POSTGRES_PASSWORD: vhtmrmfptm1!
      POSTGRES_USERNAME: postgres
    ports: 
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build:
      context: ./server/studyTime
    ports: 
      - 8080:8080
volumes:
  db: